// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package cn.ponfee.commons.serial;

public final class PersonProtobuf {
  private PersonProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code PhoneType}
   */
  public enum PhoneType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MOBILE = 0;</code>
     */
    MOBILE(0),
    /**
     * <code>HOME = 1;</code>
     */
    HOME(1),
    /**
     * <code>WORK = 2;</code>
     */
    WORK(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MOBILE = 0;</code>
     */
    public static final int MOBILE_VALUE = 0;
    /**
     * <code>HOME = 1;</code>
     */
    public static final int HOME_VALUE = 1;
    /**
     * <code>WORK = 2;</code>
     */
    public static final int WORK_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PhoneType valueOf(int value) {
      return forNumber(value);
    }

    public static PhoneType forNumber(int value) {
      switch (value) {
        case 0: return MOBILE;
        case 1: return HOME;
        case 2: return WORK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PhoneType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
            public PhoneType findValueByNumber(int number) {
              return PhoneType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cn.ponfee.commons.serial.PersonProtobuf.getDescriptor().getEnumTypes().get(0);
    }

    private static final PhoneType[] VALUES = values();

    public static PhoneType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PhoneType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PhoneType)
  }

  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 3;</code>
     */
    int getAge();

    /**
     * <code>.Addr addr = 4;</code>
     */
    boolean hasAddr();
    /**
     * <code>.Addr addr = 4;</code>
     */
    cn.ponfee.commons.serial.PersonProtobuf.Addr getAddr();
    /**
     * <code>.Addr addr = 4;</code>
     */
    cn.ponfee.commons.serial.PersonProtobuf.AddrOrBuilder getAddrOrBuilder();

    /**
     * <code>repeated .Phone phone = 5;</code>
     */
    java.util.List<cn.ponfee.commons.serial.PersonProtobuf.Phone> 
        getPhoneList();
    /**
     * <code>repeated .Phone phone = 5;</code>
     */
    cn.ponfee.commons.serial.PersonProtobuf.Phone getPhone(int index);
    /**
     * <code>repeated .Phone phone = 5;</code>
     */
    int getPhoneCount();
    /**
     * <code>repeated .Phone phone = 5;</code>
     */
    java.util.List<? extends cn.ponfee.commons.serial.PersonProtobuf.PhoneOrBuilder> 
        getPhoneOrBuilderList();
    /**
     * <code>repeated .Phone phone = 5;</code>
     */
    cn.ponfee.commons.serial.PersonProtobuf.PhoneOrBuilder getPhoneOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
      phone_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              age_ = input.readInt32();
              break;
            }
            case 34: {
              cn.ponfee.commons.serial.PersonProtobuf.Addr.Builder subBuilder = null;
              if (addr_ != null) {
                subBuilder = addr_.toBuilder();
              }
              addr_ = input.readMessage(cn.ponfee.commons.serial.PersonProtobuf.Addr.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(addr_);
                addr_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) != 0)) {
                phone_ = new java.util.ArrayList<cn.ponfee.commons.serial.PersonProtobuf.Phone>();
                mutable_bitField0_ |= 0x00000010;
              }
              phone_.add(
                  input.readMessage(cn.ponfee.commons.serial.PersonProtobuf.Phone.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) != 0)) {
          phone_ = java.util.Collections.unmodifiableList(phone_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.ponfee.commons.serial.PersonProtobuf.internal_static_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.ponfee.commons.serial.PersonProtobuf.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.ponfee.commons.serial.PersonProtobuf.Person.class, cn.ponfee.commons.serial.PersonProtobuf.Person.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <code>int32 age = 3;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int ADDR_FIELD_NUMBER = 4;
    private cn.ponfee.commons.serial.PersonProtobuf.Addr addr_;
    /**
     * <code>.Addr addr = 4;</code>
     */
    public boolean hasAddr() {
      return addr_ != null;
    }
    /**
     * <code>.Addr addr = 4;</code>
     */
    public cn.ponfee.commons.serial.PersonProtobuf.Addr getAddr() {
      return addr_ == null ? cn.ponfee.commons.serial.PersonProtobuf.Addr.getDefaultInstance() : addr_;
    }
    /**
     * <code>.Addr addr = 4;</code>
     */
    public cn.ponfee.commons.serial.PersonProtobuf.AddrOrBuilder getAddrOrBuilder() {
      return getAddr();
    }

    public static final int PHONE_FIELD_NUMBER = 5;
    private java.util.List<cn.ponfee.commons.serial.PersonProtobuf.Phone> phone_;
    /**
     * <code>repeated .Phone phone = 5;</code>
     */
    public java.util.List<cn.ponfee.commons.serial.PersonProtobuf.Phone> getPhoneList() {
      return phone_;
    }
    /**
     * <code>repeated .Phone phone = 5;</code>
     */
    public java.util.List<? extends cn.ponfee.commons.serial.PersonProtobuf.PhoneOrBuilder> 
        getPhoneOrBuilderList() {
      return phone_;
    }
    /**
     * <code>repeated .Phone phone = 5;</code>
     */
    public int getPhoneCount() {
      return phone_.size();
    }
    /**
     * <code>repeated .Phone phone = 5;</code>
     */
    public cn.ponfee.commons.serial.PersonProtobuf.Phone getPhone(int index) {
      return phone_.get(index);
    }
    /**
     * <code>repeated .Phone phone = 5;</code>
     */
    public cn.ponfee.commons.serial.PersonProtobuf.PhoneOrBuilder getPhoneOrBuilder(
        int index) {
      return phone_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (age_ != 0) {
        output.writeInt32(3, age_);
      }
      if (addr_ != null) {
        output.writeMessage(4, getAddr());
      }
      for (int i = 0; i < phone_.size(); i++) {
        output.writeMessage(5, phone_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      if (addr_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getAddr());
      }
      for (int i = 0; i < phone_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, phone_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.ponfee.commons.serial.PersonProtobuf.Person)) {
        return super.equals(obj);
      }
      cn.ponfee.commons.serial.PersonProtobuf.Person other = (cn.ponfee.commons.serial.PersonProtobuf.Person) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (hasAddr() != other.hasAddr()) return false;
      if (hasAddr()) {
        if (!getAddr()
            .equals(other.getAddr())) return false;
      }
      if (!getPhoneList()
          .equals(other.getPhoneList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      if (hasAddr()) {
        hash = (37 * hash) + ADDR_FIELD_NUMBER;
        hash = (53 * hash) + getAddr().hashCode();
      }
      if (getPhoneCount() > 0) {
        hash = (37 * hash) + PHONE_FIELD_NUMBER;
        hash = (53 * hash) + getPhoneList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.ponfee.commons.serial.PersonProtobuf.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.ponfee.commons.serial.PersonProtobuf.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Person)
        cn.ponfee.commons.serial.PersonProtobuf.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.ponfee.commons.serial.PersonProtobuf.internal_static_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.ponfee.commons.serial.PersonProtobuf.internal_static_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.ponfee.commons.serial.PersonProtobuf.Person.class, cn.ponfee.commons.serial.PersonProtobuf.Person.Builder.class);
      }

      // Construct using cn.ponfee.commons.serial.PersonProtobuf.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPhoneFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        age_ = 0;

        if (addrBuilder_ == null) {
          addr_ = null;
        } else {
          addr_ = null;
          addrBuilder_ = null;
        }
        if (phoneBuilder_ == null) {
          phone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          phoneBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.ponfee.commons.serial.PersonProtobuf.internal_static_Person_descriptor;
      }

      @java.lang.Override
      public cn.ponfee.commons.serial.PersonProtobuf.Person getDefaultInstanceForType() {
        return cn.ponfee.commons.serial.PersonProtobuf.Person.getDefaultInstance();
      }

      @java.lang.Override
      public cn.ponfee.commons.serial.PersonProtobuf.Person build() {
        cn.ponfee.commons.serial.PersonProtobuf.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.ponfee.commons.serial.PersonProtobuf.Person buildPartial() {
        cn.ponfee.commons.serial.PersonProtobuf.Person result = new cn.ponfee.commons.serial.PersonProtobuf.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        result.age_ = age_;
        if (addrBuilder_ == null) {
          result.addr_ = addr_;
        } else {
          result.addr_ = addrBuilder_.build();
        }
        if (phoneBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0)) {
            phone_ = java.util.Collections.unmodifiableList(phone_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.phone_ = phone_;
        } else {
          result.phone_ = phoneBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.ponfee.commons.serial.PersonProtobuf.Person) {
          return mergeFrom((cn.ponfee.commons.serial.PersonProtobuf.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.ponfee.commons.serial.PersonProtobuf.Person other) {
        if (other == cn.ponfee.commons.serial.PersonProtobuf.Person.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.hasAddr()) {
          mergeAddr(other.getAddr());
        }
        if (phoneBuilder_ == null) {
          if (!other.phone_.isEmpty()) {
            if (phone_.isEmpty()) {
              phone_ = other.phone_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensurePhoneIsMutable();
              phone_.addAll(other.phone_);
            }
            onChanged();
          }
        } else {
          if (!other.phone_.isEmpty()) {
            if (phoneBuilder_.isEmpty()) {
              phoneBuilder_.dispose();
              phoneBuilder_ = null;
              phone_ = other.phone_;
              bitField0_ = (bitField0_ & ~0x00000010);
              phoneBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPhoneFieldBuilder() : null;
            } else {
              phoneBuilder_.addAllMessages(other.phone_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.ponfee.commons.serial.PersonProtobuf.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.ponfee.commons.serial.PersonProtobuf.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 3;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 3;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 3;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private cn.ponfee.commons.serial.PersonProtobuf.Addr addr_;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.ponfee.commons.serial.PersonProtobuf.Addr, cn.ponfee.commons.serial.PersonProtobuf.Addr.Builder, cn.ponfee.commons.serial.PersonProtobuf.AddrOrBuilder> addrBuilder_;
      /**
       * <code>.Addr addr = 4;</code>
       */
      public boolean hasAddr() {
        return addrBuilder_ != null || addr_ != null;
      }
      /**
       * <code>.Addr addr = 4;</code>
       */
      public cn.ponfee.commons.serial.PersonProtobuf.Addr getAddr() {
        if (addrBuilder_ == null) {
          return addr_ == null ? cn.ponfee.commons.serial.PersonProtobuf.Addr.getDefaultInstance() : addr_;
        } else {
          return addrBuilder_.getMessage();
        }
      }
      /**
       * <code>.Addr addr = 4;</code>
       */
      public Builder setAddr(cn.ponfee.commons.serial.PersonProtobuf.Addr value) {
        if (addrBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          addr_ = value;
          onChanged();
        } else {
          addrBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Addr addr = 4;</code>
       */
      public Builder setAddr(
          cn.ponfee.commons.serial.PersonProtobuf.Addr.Builder builderForValue) {
        if (addrBuilder_ == null) {
          addr_ = builderForValue.build();
          onChanged();
        } else {
          addrBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Addr addr = 4;</code>
       */
      public Builder mergeAddr(cn.ponfee.commons.serial.PersonProtobuf.Addr value) {
        if (addrBuilder_ == null) {
          if (addr_ != null) {
            addr_ =
              cn.ponfee.commons.serial.PersonProtobuf.Addr.newBuilder(addr_).mergeFrom(value).buildPartial();
          } else {
            addr_ = value;
          }
          onChanged();
        } else {
          addrBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Addr addr = 4;</code>
       */
      public Builder clearAddr() {
        if (addrBuilder_ == null) {
          addr_ = null;
          onChanged();
        } else {
          addr_ = null;
          addrBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Addr addr = 4;</code>
       */
      public cn.ponfee.commons.serial.PersonProtobuf.Addr.Builder getAddrBuilder() {
        
        onChanged();
        return getAddrFieldBuilder().getBuilder();
      }
      /**
       * <code>.Addr addr = 4;</code>
       */
      public cn.ponfee.commons.serial.PersonProtobuf.AddrOrBuilder getAddrOrBuilder() {
        if (addrBuilder_ != null) {
          return addrBuilder_.getMessageOrBuilder();
        } else {
          return addr_ == null ?
              cn.ponfee.commons.serial.PersonProtobuf.Addr.getDefaultInstance() : addr_;
        }
      }
      /**
       * <code>.Addr addr = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.ponfee.commons.serial.PersonProtobuf.Addr, cn.ponfee.commons.serial.PersonProtobuf.Addr.Builder, cn.ponfee.commons.serial.PersonProtobuf.AddrOrBuilder> 
          getAddrFieldBuilder() {
        if (addrBuilder_ == null) {
          addrBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.ponfee.commons.serial.PersonProtobuf.Addr, cn.ponfee.commons.serial.PersonProtobuf.Addr.Builder, cn.ponfee.commons.serial.PersonProtobuf.AddrOrBuilder>(
                  getAddr(),
                  getParentForChildren(),
                  isClean());
          addr_ = null;
        }
        return addrBuilder_;
      }

      private java.util.List<cn.ponfee.commons.serial.PersonProtobuf.Phone> phone_ =
        java.util.Collections.emptyList();
      private void ensurePhoneIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          phone_ = new java.util.ArrayList<cn.ponfee.commons.serial.PersonProtobuf.Phone>(phone_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.ponfee.commons.serial.PersonProtobuf.Phone, cn.ponfee.commons.serial.PersonProtobuf.Phone.Builder, cn.ponfee.commons.serial.PersonProtobuf.PhoneOrBuilder> phoneBuilder_;

      /**
       * <code>repeated .Phone phone = 5;</code>
       */
      public java.util.List<cn.ponfee.commons.serial.PersonProtobuf.Phone> getPhoneList() {
        if (phoneBuilder_ == null) {
          return java.util.Collections.unmodifiableList(phone_);
        } else {
          return phoneBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Phone phone = 5;</code>
       */
      public int getPhoneCount() {
        if (phoneBuilder_ == null) {
          return phone_.size();
        } else {
          return phoneBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Phone phone = 5;</code>
       */
      public cn.ponfee.commons.serial.PersonProtobuf.Phone getPhone(int index) {
        if (phoneBuilder_ == null) {
          return phone_.get(index);
        } else {
          return phoneBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Phone phone = 5;</code>
       */
      public Builder setPhone(
          int index, cn.ponfee.commons.serial.PersonProtobuf.Phone value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.set(index, value);
          onChanged();
        } else {
          phoneBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Phone phone = 5;</code>
       */
      public Builder setPhone(
          int index, cn.ponfee.commons.serial.PersonProtobuf.Phone.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.set(index, builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Phone phone = 5;</code>
       */
      public Builder addPhone(cn.ponfee.commons.serial.PersonProtobuf.Phone value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.add(value);
          onChanged();
        } else {
          phoneBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Phone phone = 5;</code>
       */
      public Builder addPhone(
          int index, cn.ponfee.commons.serial.PersonProtobuf.Phone value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.add(index, value);
          onChanged();
        } else {
          phoneBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Phone phone = 5;</code>
       */
      public Builder addPhone(
          cn.ponfee.commons.serial.PersonProtobuf.Phone.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.add(builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Phone phone = 5;</code>
       */
      public Builder addPhone(
          int index, cn.ponfee.commons.serial.PersonProtobuf.Phone.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.add(index, builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Phone phone = 5;</code>
       */
      public Builder addAllPhone(
          java.lang.Iterable<? extends cn.ponfee.commons.serial.PersonProtobuf.Phone> values) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, phone_);
          onChanged();
        } else {
          phoneBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Phone phone = 5;</code>
       */
      public Builder clearPhone() {
        if (phoneBuilder_ == null) {
          phone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          phoneBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Phone phone = 5;</code>
       */
      public Builder removePhone(int index) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.remove(index);
          onChanged();
        } else {
          phoneBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Phone phone = 5;</code>
       */
      public cn.ponfee.commons.serial.PersonProtobuf.Phone.Builder getPhoneBuilder(
          int index) {
        return getPhoneFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Phone phone = 5;</code>
       */
      public cn.ponfee.commons.serial.PersonProtobuf.PhoneOrBuilder getPhoneOrBuilder(
          int index) {
        if (phoneBuilder_ == null) {
          return phone_.get(index);  } else {
          return phoneBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Phone phone = 5;</code>
       */
      public java.util.List<? extends cn.ponfee.commons.serial.PersonProtobuf.PhoneOrBuilder> 
           getPhoneOrBuilderList() {
        if (phoneBuilder_ != null) {
          return phoneBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(phone_);
        }
      }
      /**
       * <code>repeated .Phone phone = 5;</code>
       */
      public cn.ponfee.commons.serial.PersonProtobuf.Phone.Builder addPhoneBuilder() {
        return getPhoneFieldBuilder().addBuilder(
            cn.ponfee.commons.serial.PersonProtobuf.Phone.getDefaultInstance());
      }
      /**
       * <code>repeated .Phone phone = 5;</code>
       */
      public cn.ponfee.commons.serial.PersonProtobuf.Phone.Builder addPhoneBuilder(
          int index) {
        return getPhoneFieldBuilder().addBuilder(
            index, cn.ponfee.commons.serial.PersonProtobuf.Phone.getDefaultInstance());
      }
      /**
       * <code>repeated .Phone phone = 5;</code>
       */
      public java.util.List<cn.ponfee.commons.serial.PersonProtobuf.Phone.Builder> 
           getPhoneBuilderList() {
        return getPhoneFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.ponfee.commons.serial.PersonProtobuf.Phone, cn.ponfee.commons.serial.PersonProtobuf.Phone.Builder, cn.ponfee.commons.serial.PersonProtobuf.PhoneOrBuilder> 
          getPhoneFieldBuilder() {
        if (phoneBuilder_ == null) {
          phoneBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cn.ponfee.commons.serial.PersonProtobuf.Phone, cn.ponfee.commons.serial.PersonProtobuf.Phone.Builder, cn.ponfee.commons.serial.PersonProtobuf.PhoneOrBuilder>(
                  phone_,
                  ((bitField0_ & 0x00000010) != 0),
                  getParentForChildren(),
                  isClean());
          phone_ = null;
        }
        return phoneBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Person)
    }

    // @@protoc_insertion_point(class_scope:Person)
    private static final cn.ponfee.commons.serial.PersonProtobuf.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.ponfee.commons.serial.PersonProtobuf.Person();
    }

    public static cn.ponfee.commons.serial.PersonProtobuf.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.ponfee.commons.serial.PersonProtobuf.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddrOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Addr)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string contry = 1;</code>
     */
    java.lang.String getContry();
    /**
     * <code>string contry = 1;</code>
     */
    com.google.protobuf.ByteString
        getContryBytes();

    /**
     * <code>string city = 2;</code>
     */
    java.lang.String getCity();
    /**
     * <code>string city = 2;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();
  }
  /**
   * Protobuf type {@code Addr}
   */
  public  static final class Addr extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Addr)
      AddrOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Addr.newBuilder() to construct.
    private Addr(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Addr() {
      contry_ = "";
      city_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Addr(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              contry_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              city_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.ponfee.commons.serial.PersonProtobuf.internal_static_Addr_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.ponfee.commons.serial.PersonProtobuf.internal_static_Addr_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.ponfee.commons.serial.PersonProtobuf.Addr.class, cn.ponfee.commons.serial.PersonProtobuf.Addr.Builder.class);
    }

    public static final int CONTRY_FIELD_NUMBER = 1;
    private volatile java.lang.Object contry_;
    /**
     * <code>string contry = 1;</code>
     */
    public java.lang.String getContry() {
      java.lang.Object ref = contry_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contry_ = s;
        return s;
      }
    }
    /**
     * <code>string contry = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContryBytes() {
      java.lang.Object ref = contry_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contry_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 2;
    private volatile java.lang.Object city_;
    /**
     * <code>string city = 2;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>string city = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getContryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, contry_);
      }
      if (!getCityBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, city_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getContryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, contry_);
      }
      if (!getCityBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, city_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.ponfee.commons.serial.PersonProtobuf.Addr)) {
        return super.equals(obj);
      }
      cn.ponfee.commons.serial.PersonProtobuf.Addr other = (cn.ponfee.commons.serial.PersonProtobuf.Addr) obj;

      if (!getContry()
          .equals(other.getContry())) return false;
      if (!getCity()
          .equals(other.getCity())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTRY_FIELD_NUMBER;
      hash = (53 * hash) + getContry().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.ponfee.commons.serial.PersonProtobuf.Addr parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Addr parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Addr parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Addr parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Addr parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Addr parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Addr parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Addr parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Addr parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Addr parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Addr parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Addr parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.ponfee.commons.serial.PersonProtobuf.Addr prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Addr}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Addr)
        cn.ponfee.commons.serial.PersonProtobuf.AddrOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.ponfee.commons.serial.PersonProtobuf.internal_static_Addr_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.ponfee.commons.serial.PersonProtobuf.internal_static_Addr_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.ponfee.commons.serial.PersonProtobuf.Addr.class, cn.ponfee.commons.serial.PersonProtobuf.Addr.Builder.class);
      }

      // Construct using cn.ponfee.commons.serial.PersonProtobuf.Addr.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        contry_ = "";

        city_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.ponfee.commons.serial.PersonProtobuf.internal_static_Addr_descriptor;
      }

      @java.lang.Override
      public cn.ponfee.commons.serial.PersonProtobuf.Addr getDefaultInstanceForType() {
        return cn.ponfee.commons.serial.PersonProtobuf.Addr.getDefaultInstance();
      }

      @java.lang.Override
      public cn.ponfee.commons.serial.PersonProtobuf.Addr build() {
        cn.ponfee.commons.serial.PersonProtobuf.Addr result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.ponfee.commons.serial.PersonProtobuf.Addr buildPartial() {
        cn.ponfee.commons.serial.PersonProtobuf.Addr result = new cn.ponfee.commons.serial.PersonProtobuf.Addr(this);
        result.contry_ = contry_;
        result.city_ = city_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.ponfee.commons.serial.PersonProtobuf.Addr) {
          return mergeFrom((cn.ponfee.commons.serial.PersonProtobuf.Addr)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.ponfee.commons.serial.PersonProtobuf.Addr other) {
        if (other == cn.ponfee.commons.serial.PersonProtobuf.Addr.getDefaultInstance()) return this;
        if (!other.getContry().isEmpty()) {
          contry_ = other.contry_;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.ponfee.commons.serial.PersonProtobuf.Addr parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.ponfee.commons.serial.PersonProtobuf.Addr) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object contry_ = "";
      /**
       * <code>string contry = 1;</code>
       */
      public java.lang.String getContry() {
        java.lang.Object ref = contry_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contry_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string contry = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContryBytes() {
        java.lang.Object ref = contry_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contry_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string contry = 1;</code>
       */
      public Builder setContry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contry_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string contry = 1;</code>
       */
      public Builder clearContry() {
        
        contry_ = getDefaultInstance().getContry();
        onChanged();
        return this;
      }
      /**
       * <code>string contry = 1;</code>
       */
      public Builder setContryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        contry_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>string city = 2;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string city = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string city = 2;</code>
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string city = 2;</code>
       */
      public Builder clearCity() {
        
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>string city = 2;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        city_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Addr)
    }

    // @@protoc_insertion_point(class_scope:Addr)
    private static final cn.ponfee.commons.serial.PersonProtobuf.Addr DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.ponfee.commons.serial.PersonProtobuf.Addr();
    }

    public static cn.ponfee.commons.serial.PersonProtobuf.Addr getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Addr>
        PARSER = new com.google.protobuf.AbstractParser<Addr>() {
      @java.lang.Override
      public Addr parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Addr(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Addr> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Addr> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.ponfee.commons.serial.PersonProtobuf.Addr getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PhoneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Phone)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string number = 1;</code>
     */
    java.lang.String getNumber();
    /**
     * <code>string number = 1;</code>
     */
    com.google.protobuf.ByteString
        getNumberBytes();

    /**
     * <code>.PhoneType type = 2;</code>
     */
    int getTypeValue();
    /**
     * <code>.PhoneType type = 2;</code>
     */
    cn.ponfee.commons.serial.PersonProtobuf.PhoneType getType();
  }
  /**
   * Protobuf type {@code Phone}
   */
  public  static final class Phone extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Phone)
      PhoneOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Phone.newBuilder() to construct.
    private Phone(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Phone() {
      number_ = "";
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Phone(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              number_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.ponfee.commons.serial.PersonProtobuf.internal_static_Phone_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.ponfee.commons.serial.PersonProtobuf.internal_static_Phone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.ponfee.commons.serial.PersonProtobuf.Phone.class, cn.ponfee.commons.serial.PersonProtobuf.Phone.Builder.class);
    }

    public static final int NUMBER_FIELD_NUMBER = 1;
    private volatile java.lang.Object number_;
    /**
     * <code>string number = 1;</code>
     */
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        number_ = s;
        return s;
      }
    }
    /**
     * <code>string number = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.PhoneType type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.PhoneType type = 2;</code>
     */
    public cn.ponfee.commons.serial.PersonProtobuf.PhoneType getType() {
      @SuppressWarnings("deprecation")
      cn.ponfee.commons.serial.PersonProtobuf.PhoneType result = cn.ponfee.commons.serial.PersonProtobuf.PhoneType.valueOf(type_);
      return result == null ? cn.ponfee.commons.serial.PersonProtobuf.PhoneType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, number_);
      }
      if (type_ != cn.ponfee.commons.serial.PersonProtobuf.PhoneType.MOBILE.getNumber()) {
        output.writeEnum(2, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, number_);
      }
      if (type_ != cn.ponfee.commons.serial.PersonProtobuf.PhoneType.MOBILE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.ponfee.commons.serial.PersonProtobuf.Phone)) {
        return super.equals(obj);
      }
      cn.ponfee.commons.serial.PersonProtobuf.Phone other = (cn.ponfee.commons.serial.PersonProtobuf.Phone) obj;

      if (!getNumber()
          .equals(other.getNumber())) return false;
      if (type_ != other.type_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.ponfee.commons.serial.PersonProtobuf.Phone parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Phone parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Phone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Phone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Phone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Phone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Phone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Phone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Phone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Phone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Phone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.ponfee.commons.serial.PersonProtobuf.Phone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.ponfee.commons.serial.PersonProtobuf.Phone prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Phone}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Phone)
        cn.ponfee.commons.serial.PersonProtobuf.PhoneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.ponfee.commons.serial.PersonProtobuf.internal_static_Phone_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.ponfee.commons.serial.PersonProtobuf.internal_static_Phone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.ponfee.commons.serial.PersonProtobuf.Phone.class, cn.ponfee.commons.serial.PersonProtobuf.Phone.Builder.class);
      }

      // Construct using cn.ponfee.commons.serial.PersonProtobuf.Phone.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        number_ = "";

        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.ponfee.commons.serial.PersonProtobuf.internal_static_Phone_descriptor;
      }

      @java.lang.Override
      public cn.ponfee.commons.serial.PersonProtobuf.Phone getDefaultInstanceForType() {
        return cn.ponfee.commons.serial.PersonProtobuf.Phone.getDefaultInstance();
      }

      @java.lang.Override
      public cn.ponfee.commons.serial.PersonProtobuf.Phone build() {
        cn.ponfee.commons.serial.PersonProtobuf.Phone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.ponfee.commons.serial.PersonProtobuf.Phone buildPartial() {
        cn.ponfee.commons.serial.PersonProtobuf.Phone result = new cn.ponfee.commons.serial.PersonProtobuf.Phone(this);
        result.number_ = number_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.ponfee.commons.serial.PersonProtobuf.Phone) {
          return mergeFrom((cn.ponfee.commons.serial.PersonProtobuf.Phone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.ponfee.commons.serial.PersonProtobuf.Phone other) {
        if (other == cn.ponfee.commons.serial.PersonProtobuf.Phone.getDefaultInstance()) return this;
        if (!other.getNumber().isEmpty()) {
          number_ = other.number_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.ponfee.commons.serial.PersonProtobuf.Phone parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.ponfee.commons.serial.PersonProtobuf.Phone) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object number_ = "";
      /**
       * <code>string number = 1;</code>
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          number_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string number = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string number = 1;</code>
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string number = 1;</code>
       */
      public Builder clearNumber() {
        
        number_ = getDefaultInstance().getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>string number = 1;</code>
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        number_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.PhoneType type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.PhoneType type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.PhoneType type = 2;</code>
       */
      public cn.ponfee.commons.serial.PersonProtobuf.PhoneType getType() {
        @SuppressWarnings("deprecation")
        cn.ponfee.commons.serial.PersonProtobuf.PhoneType result = cn.ponfee.commons.serial.PersonProtobuf.PhoneType.valueOf(type_);
        return result == null ? cn.ponfee.commons.serial.PersonProtobuf.PhoneType.UNRECOGNIZED : result;
      }
      /**
       * <code>.PhoneType type = 2;</code>
       */
      public Builder setType(cn.ponfee.commons.serial.PersonProtobuf.PhoneType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.PhoneType type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Phone)
    }

    // @@protoc_insertion_point(class_scope:Phone)
    private static final cn.ponfee.commons.serial.PersonProtobuf.Phone DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.ponfee.commons.serial.PersonProtobuf.Phone();
    }

    public static cn.ponfee.commons.serial.PersonProtobuf.Phone getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Phone>
        PARSER = new com.google.protobuf.AbstractParser<Phone>() {
      @java.lang.Override
      public Phone parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Phone(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Phone> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Phone> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.ponfee.commons.serial.PersonProtobuf.Phone getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Addr_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Addr_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Phone_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Phone_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\"[\n\006Person\022\n\n\002id\030\001 \001(\005\022\014\n\004" +
      "name\030\002 \001(\t\022\013\n\003age\030\003 \001(\005\022\023\n\004addr\030\004 \001(\0132\005." +
      "Addr\022\025\n\005phone\030\005 \003(\0132\006.Phone\"$\n\004Addr\022\016\n\006c" +
      "ontry\030\001 \001(\t\022\014\n\004city\030\002 \001(\t\"1\n\005Phone\022\016\n\006nu" +
      "mber\030\001 \001(\t\022\030\n\004type\030\002 \001(\0162\n.PhoneType*+\n\t" +
      "PhoneType\022\n\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020" +
      "\002B,\n\032cn.ponfee.commons.serialB\016PersonP" +
      "rotobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Person_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", "Addr", "Phone", });
    internal_static_Addr_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Addr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Addr_descriptor,
        new java.lang.String[] { "Contry", "City", });
    internal_static_Phone_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Phone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Phone_descriptor,
        new java.lang.String[] { "Number", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
